### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by asassoye** [Rival420/Spynet#2]
When i use this as stated in the documentation
```sh
$ python Spynet.py -t 10.96.1.0/27
```
i have this error:
```
Traceback (most recent call last):
  File "/home/asassoye/git/Rival420/Spynet/Spynet.py", line 443, in <module>
    main(options)
  File "/home/asassoye/git/Rival420/Spynet/Spynet.py", line 416, in main
    host_results = discover_host(options.target)
  File "/home/asassoye/git/Rival420/Spynet/Spynet.py", line 158, in discover_host
    answered_list = scapy.srp(arp_request_broadcast, timeout=1, verbose=False)[0]
  File "/home/asassoye/.local/lib/python3.9/site-packages/scapy/sendrecv.py", line 675, in srp
    s = iface.l2socket()(promisc=promisc, iface=iface,
  File "/home/asassoye/.local/lib/python3.9/site-packages/scapy/arch/linux.py", line 486, in __init__
    self.ins = socket.socket(
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted
```
I'm actually on Arch Linux distribution and i use this to launch the script: 
|     | Version   |
|-------|--------------|
| Python | 3.9.5 |
| Scapy | 2.4.5   |
| GitPython | 3.1.17 |

Any idea what the problem is? :)

**Comment by Rival420** [comment]
Permission error, maybe use sudo?
